version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis:latest'
  nginx:
    depends_on:
      - api
      - client
      # essential for nginx to restart if it crashes due to routing of whole application
    restart: always
      # Using custom image for nginx
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
      # service name changed to "api" instead of "server" to make it easier with working with nginx
  api:
    build:
      dockerfile: Dockerfile.dev
      # Use context as pathway to file
      context: ./server
    volumes:
      # Dont overwrite node_modules
      - /app/node_modules
      # everying within the server folder should be shared with the app folder
      - ./server:/app
    environment:
      # Used default values below from the Docs of the image on Dockerhub 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
